<?php

namespace Tests\Feature;

use App\Trending;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Redis;
use Tests\TestCase;

class TrendingThreadsTest extends TestCase
{
    use DatabaseMigrations;
    
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->trending = new Trending();
        $this->trending->reset();
    }
    
    /** @test */
    public function it_increments_score_each_time_it_is_read()
    {
        $this->assertCount(0, $this->trending->get());
        
        $thread = create('App\Thread');
        
        $this->call('GET', $thread->path());
        
        //dd($trending);
    
        $this->assertCount(1, $trending = $this->trending->get());
    
        $this->assertEquals($thread->title, $trending[0]->title);
    
        //dd($d);
    }
    

}
